name: RCGroup
description: A collection of Player characters.
version: ${project.version}#${build.number}
author: Almon
website: raid-craft.de

main de.raidcraft.rcgroups.GroupsPlugin
database: false
depend: [RaidCraft-API]